
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author estudiante
 */
public class InterfazEmpleado extends javax.swing.JFrame {

    /**
     * Creates new form InterfazEmpleado
     */
    Pila a = new Pila();
    
    Institucion inst = new Institucion();
    ListaDobleAmbiente lista = new  ListaDobleAmbiente();
    DefaultTableModel tabla = new DefaultTableModel();
    public InterfazEmpleado() throws IOException {
        initComponents();
        limpiarFormEmpleado();
        // 
        
        this.tabla.addColumn("NOMBRE");
        this.tabla.addColumn("APELLIDO");
        this.tabla.addColumn("SEXO");
        this.tabla.addColumn("EDAD");
        this.tabla.addColumn("SUELDO");
        
        
        this.jTableEmpleado.setModel(tabla);
        
        this.setLocationRelativeTo(null);
        String nombre = this.jTextFieldNombre.getText();
        System.out.println(nombre);
        
        
        
        a.mostrar();
        
        
        // 
        this.jLabel3.setText("sexo");
        
        
        this.jTextFieldInstitucionUbicacion.setText("");
        this.jTextFieldNombreInst.setText("");
        
        
        // auto ajustando imagen
//        ImageIcon imgIcon = new ImageIcon(getClass().getResource("/imagenes/paisaje.jpg"));
//        Image imgEscalada = imgIcon.getImage().getScaledInstance(jLabelFondo.getWidth(),
//        jLabelFondo.getHeight(), Image.SCALE_SMOOTH);
//        Icon iconoEscalado = new ImageIcon(imgEscalada);
//        jLabelFondo.setIcon(iconoEscalado);
        llenarComboBox();
        
        
    }
    
    void llenarComboBox() throws IOException{
        ObjectInputStream arch = null;
        String nomArch = "Institucion.dat";
        try {
            arch = new ObjectInputStream(new FileInputStream(nomArch));
            
            while(true){
                
                Institucion inst = (Institucion)arch.readObject();
                String nombre = String.valueOf(inst.getCodigo()) + "-";
                nombre += inst.getNombre();
                this.jComboBoxInstituciones.addItem(nombre);
            }
            
        } catch (Exception e) {
        }finally{
            try {
                arch.close();
            } catch (IOException ex) {
                Logger.getLogger(InterfazListar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }
    
    
    void limpiarFormEmpleado(){
        this.jTextFieldNombre.setText("");
        this.jTextFieldApellido.setText("");
        this.jTextFieldEdad.setText("0");
        this.jTextFieldSueldo.setText("0");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGrupoSexo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEmpleado = new javax.swing.JTable();
        jButtonEmpleadoJoven = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButtonVolverInicio = new javax.swing.JButton();
        jProgressBarPila = new javax.swing.JProgressBar();
        jPanelInstitucion = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldNombre = new javax.swing.JTextField();
        jTextFieldApellido = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jRadioButtonMasculino = new javax.swing.JRadioButton();
        jRadioButtonFemenino = new javax.swing.JRadioButton();
        jRadioButtonOtros = new javax.swing.JRadioButton();
        jTextFieldEdad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldSueldo = new javax.swing.JTextField();
        jButtonAdicionarAmbiente1 = new javax.swing.JButton();
        jComboBoxInstituciones = new javax.swing.JComboBox<>();
        jPanelAmbientes = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldAmbienteNombrer = new javax.swing.JTextField();
        jTextFieldAmbienteUbi = new javax.swing.JTextField();
        jTextFieldAmbieneCantidad = new javax.swing.JTextField();
        jButtonAdicionarAmbiente = new javax.swing.JButton();
        jButtonAdicionar1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNombreInst = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldInstitucionUbicacion = new javax.swing.JTextField();
        jButtonGuardarPila = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableEmpleado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTableEmpleado);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 10, 270, 280));

        jButtonEmpleadoJoven.setText("Empleado Joven");
        jButtonEmpleadoJoven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpleadoJovenActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEmpleadoJoven, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        jButton2.setText("Ordenar Empleado");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, -1, -1));

        jButtonVolverInicio.setText("Volver");
        jButtonVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverInicioActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVolverInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 440, -1, -1));

        jProgressBarPila.setMaximum(5);
        jPanel1.add(jProgressBarPila, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, -1, -1));

        jPanelInstitucion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jPanelInstitucion.setName("hola"); // NOI18N

        jLabel1.setText("Nombre");

        jTextFieldNombre.setText("hola a todosç");

        jTextFieldApellido.setText("hola a todosç");

        jLabel2.setText("Apellido");

        jLabel3.setText("Sexo");

        ButtonGrupoSexo.add(jRadioButtonMasculino);
        jRadioButtonMasculino.setText("Masculino");

        ButtonGrupoSexo.add(jRadioButtonFemenino);
        jRadioButtonFemenino.setText("Femenino");

        ButtonGrupoSexo.add(jRadioButtonOtros);
        jRadioButtonOtros.setText("Otros");

        jTextFieldEdad.setText("hola a todosç");

        jLabel4.setText("Edad");

        jLabel5.setText("Sueldo");

        jTextFieldSueldo.setText("hola a todosç");

        jButtonAdicionarAmbiente1.setText("Adiconar Empleado");
        jButtonAdicionarAmbiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarAmbiente1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelInstitucionLayout = new javax.swing.GroupLayout(jPanelInstitucion);
        jPanelInstitucion.setLayout(jPanelInstitucionLayout);
        jPanelInstitucionLayout.setHorizontalGroup(
            jPanelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelInstitucionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelInstitucionLayout.createSequentialGroup()
                        .addComponent(jComboBoxInstituciones, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelInstitucionLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addGap(23, 23, 23)
                        .addGroup(jPanelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonMasculino)
                            .addComponent(jRadioButtonFemenino)
                            .addComponent(jRadioButtonOtros))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelInstitucionLayout.createSequentialGroup()
                        .addGroup(jPanelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInstitucionLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInstitucionLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelInstitucionLayout.createSequentialGroup()
                                .addGroup(jPanelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanelInstitucionLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanelInstitucionLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 27, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInstitucionLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jButtonAdicionarAmbiente1)))
                        .addContainerGap())))
        );
        jPanelInstitucionLayout.setVerticalGroup(
            jPanelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelInstitucionLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jComboBoxInstituciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanelInstitucionLayout.createSequentialGroup()
                        .addComponent(jRadioButtonMasculino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonFemenino)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonOtros)))
                .addGap(12, 12, 12)
                .addGroup(jPanelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(7, 7, 7)
                .addGroup(jPanelInstitucionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(jButtonAdicionarAmbiente1)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelInstitucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 190, 390));

        jPanelAmbientes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel8.setText("Nombre");

        jLabel9.setText("Ubicación");

        jLabel10.setText("Cantidad");

        jButtonAdicionarAmbiente.setText("Adiconar");
        jButtonAdicionarAmbiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarAmbienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelAmbientesLayout = new javax.swing.GroupLayout(jPanelAmbientes);
        jPanelAmbientes.setLayout(jPanelAmbientesLayout);
        jPanelAmbientesLayout.setHorizontalGroup(
            jPanelAmbientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAmbientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAmbientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAmbientesLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldAmbienteNombrer, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAmbientesLayout.createSequentialGroup()
                        .addGroup(jPanelAmbientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelAmbientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAmbienteUbi, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldAmbieneCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonAdicionarAmbiente, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanelAmbientesLayout.setVerticalGroup(
            jPanelAmbientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAmbientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelAmbientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldAmbienteNombrer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAmbientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldAmbienteUbi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelAmbientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldAmbieneCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAdicionarAmbiente)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelAmbientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 190, 160));

        jButtonAdicionar1.setText("Adiconar");
        jButtonAdicionar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionar1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdicionar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel6.setText("Nombre Inst");

        jTextFieldNombreInst.setText("hola a todosç");

        jLabel7.setText("Ubicacion");

        jTextFieldInstitucionUbicacion.setText("hola a todosç");

        jButtonGuardarPila.setText("Guardar Institucion");
        jButtonGuardarPila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarPilaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextFieldInstitucionUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNombreInst, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jButtonGuardarPila)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNombreInst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldInstitucionUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButtonGuardarPila)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 190, 150));

        jLabelFondo.setBackground(new java.awt.Color(153, 153, 255));
        jLabelFondo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabelFondo.setOpaque(true);
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    public int getCodigoInst(int numero) throws IOException{
        int nuevo_codigo = 0;
        // retorna el nuevo codigo y actualiza el archivo
        // numero  1 => inst
        // numero  2 => empleado
        // numero 3 => ambiente
        String nomArch = "Contador.dat";
        boolean flag = false;
        ObjectInputStream arch = null; // input (lectura)
        ObjectOutputStream archAux = null; // output (escritura)

       
        
        try {
            arch = new ObjectInputStream(new FileInputStream(nomArch));
            archAux = new ObjectOutputStream(new FileOutputStream("copiaContador.dat", true));
            
            while(true){
                Contadores c = (Contadores)arch.readObject();
                if(numero == 1){
                    c.setCodigoInstitucion(c.getCodigoInstitucion() + 1);
                    nuevo_codigo = c.getCodigoInstitucion();
                
                }
                if(numero == 2){
                    c.setCodigoEmpleado(c.getCodigoEmpleado()+ 1);
                    nuevo_codigo = c.getCodigoEmpleado();
                }
                
                
                if(numero == 3){
                    c.setCodigoAmbiente(c.getCodigoAmbiente()+ 1);
                    nuevo_codigo = c.getCodigoAmbiente();
                }
                archAux.writeObject(c);
                flag = true;

            }

            
            
            
        } catch (Exception e) {
        }finally {
            arch.close();
            
        
            archAux.close();
            
            
            
            if(flag != true)
                JOptionPane.showMessageDialog(null, "NO ENCONTRADO");
            else{
                JOptionPane.showMessageDialog(null, "contador de inst actualizado");

            }
            
            File F1 = new File(nomArch); // empleadito.dat
            File F2 = new File("copiaContador.dat"); // auxiliar
            F1.delete();
            F2.renameTo(F1);
        }
        
        return nuevo_codigo;
    }
    private void jButtonGuardarPilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarPilaActionPerformed
        String nomArch = "Institucion.dat";
        // 
        try {
            inst.setCodigo(getCodigoInst(1));
        } catch (IOException ex) {
            Logger.getLogger(InterfazEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.out.println("codigo de inst" + inst.getCodigo());
        inst.setNombre(this.jTextFieldNombreInst.getText());
        inst.setUbicaccion(this.jTextFieldInstitucionUbicacion.getText());
        inst.setP(a);
        
        try{
            ObjectOutputStream arch = null;
            if(new File(nomArch).exists())
                arch = new AddObjectOutputStream(new FileOutputStream(nomArch, true));
            else
                arch = new ObjectOutputStream(new FileOutputStream(nomArch, true));
            
            
            arch.writeObject(inst);
            a = new Pila(); 
            arch.close();   
            JOptionPane.showMessageDialog(null, "Institucion adicionada correctamente");
            this.jTextFieldInstitucionUbicacion.setText("");
            this.jTextFieldNombreInst.setText("");
          
        } catch (Exception e) {
               
            System.out.println("adicionar "  + e);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButtonGuardarPilaActionPerformed
    
    public void mostrarTabla(){
        tabla.setNumRows(0);
            limpiarFormEmpleado();
            Pila aux = new Pila();
            while(!a.esVacia()){
                Empleado ee = (Empleado)a.eliminar();
                aux.adicionar((Object)ee);
                String datos[] = new String[5];
                datos[0] = ee.getNombre();
                datos[1] = ee.getApellido();
                datos[2] = ee.getSexo();
                datos[3] = ee.getEdad() + "";
                datos[4] = ee.getSueldo() + "";
                
                tabla.addRow(datos);
            }
            
            a.vaciar(aux);
            
    }
    private void jButtonEmpleadoJovenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpleadoJovenActionPerformed
        
        int mn = 1000000;
        Pila aux = new Pila();
        System.out.println("jovn");
        while(!a.esVacia()){    
            Empleado e1 = (Empleado)a.eliminar();
            e1.mostrar();
            if(mn > e1.getEdad()){
                mn = e1.getEdad();
            }
            aux.adicionar(e1);
            
        }
        System.out.println(mn);
        
        while(!aux.esVacia()){
            Empleado e1 = (Empleado)aux.eliminar();
            if(mn == e1.getEdad()){
                this.jTextFieldNombre.setText(e1.getNombre());
                this.jTextFieldApellido.setText(e1.getApellido());
                
                this.jTextFieldEdad.setText(e1.getEdad() + "");
                this.jTextFieldSueldo.setText(e1.getSueldo() + "");
            }
            a.adicionar(e1);
            
        }
    }//GEN-LAST:event_jButtonEmpleadoJovenActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Pila aux = new Pila();
        Pila resp = new Pila();
        System.out.println("datos antes de ordenar");
        a.mostrar();
        System.out.println("ordendnado");
        while(! a.esVacia()){
            Empleado mn = (Empleado) a.eliminar();
            aux.adicionar((Object)mn);
            while(! a.esVacia()){
                Empleado comp = (Empleado) a.eliminar();
                if(comp.getEdad() < mn.getEdad()  ){
                    mn = comp;
                }
                aux.adicionar((Object)comp);
            }
            
            while(! aux.esVacia()){
                Empleado comp = (Empleado) aux.eliminar();
                if(comp.getEdad() == mn.getEdad()  ){
                    resp.adicionar(comp);
                }else{
                    a.adicionar((Object)comp);
                }
            }
            
            
            
        }
        a.vaciar(resp);
        a.mostrar();
        mostrarTabla();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverInicioActionPerformed
        // TODO add your handling code here:
        InterfazInicio ii = new InterfazInicio();
        ii.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVolverInicioActionPerformed

    private void jButtonAdicionarAmbienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarAmbienteActionPerformed
        // TODO add your handling code here:
        Ambiente amb = new Ambiente();
        
        amb.setNombre(this.jTextFieldAmbienteNombrer.getText());
        amb.setUbicacion(this.jTextFieldAmbienteUbi.getText());
        
        boolean flag = true;
        int cantidad = 0;
        try {
            cantidad = Integer.parseInt(this.jTextFieldAmbieneCantidad.getText());
            amb.setCapacidad(cantidad);
        } catch (Exception e) {
            flag = false;
            JOptionPane.showMessageDialog(null, "La cantidad debe ser un numero entero");
        }
        
        if(flag){
            lista.adicionar(amb);
            System.out.println("mostrando  lista");
            lista.mostrar();
            
            this.jTextFieldAmbieneCantidad.setText("0");
            this.jTextFieldAmbienteNombrer.setText("");
            this.jTextFieldAmbienteUbi.setText("");
        }
        
        
        
        
    }//GEN-LAST:event_jButtonAdicionarAmbienteActionPerformed

    private void jButtonAdicionar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAdicionar1ActionPerformed

    private void jButtonAdicionarAmbiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarAmbiente1ActionPerformed
        // TODO add your handling code here:
        Empleado emp = new Empleado();
        
        String cadenita = this.jComboBoxInstituciones.getSelectedItem().toString();
        System.out.println("texto seleccionado " + cadenita);
        String[] codigo1 = cadenita.split("-");
        System.out.println(codigo1[0]);
        
        int codigo_inst = Integer.parseInt(codigo1[0]);

        try {
            emp.setCodigo(getCodigoInst(2));
        } catch (IOException ex) {
            Logger.getLogger(InterfazEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        emp.setNombre(this.jTextFieldNombre.getText());
        emp.setApellido(this.jTextFieldApellido.getText());
        if(this.jRadioButtonFemenino.isSelected()){
            emp.setSexo(this.jRadioButtonFemenino.getText());
        }
        if(this.jRadioButtonMasculino.isSelected()){
            emp.setSexo(this.jRadioButtonMasculino.getText());
        }
        if(this.jRadioButtonOtros.isSelected()){
            emp.setSexo(this.jRadioButtonOtros.getText());
        }
        
        boolean flag = true;
        int edad = 0;
        
        try {
            edad = Integer.parseInt(this.jTextFieldEdad.getText());
            emp.setEdad(edad);
        } catch (Exception e) {
            flag = false;
            JOptionPane.showMessageDialog(null, "La edad debe ser un numero entero");
        }
        
        double sueldo = 0;
        
        try {
            sueldo = Double.parseDouble(this.jTextFieldSueldo.getText());
            emp.setSueldo(sueldo);
        } catch (Exception e) {
            flag = false;
            JOptionPane.showMessageDialog(null, "El  sueldo debe ser un numero decimal");
        }

        try {
            adicionarEmpleado(codigo_inst, emp);
        } catch (IOException ex) {
            Logger.getLogger(InterfazEmpleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButtonAdicionarAmbiente1ActionPerformed

    
    void adicionarEmpleado(int codigo, Empleado emp) throws IOException{
        String nomArch = "Institucion.dat";
        boolean flag = false;
        ObjectInputStream arch = null; // input (lectura)
        ObjectOutputStream archAux = null; // output (escritura)

       
        
        try {
            arch = new ObjectInputStream(new FileInputStream(nomArch));
            archAux = new ObjectOutputStream(new FileOutputStream("copiaInstitucion.dat", true));
            
            while(true){
                Institucion inst = (Institucion)arch.readObject();
                if(inst.getCodigo() == codigo){
                    inst.getP().adicionar(emp);
                    flag = true;
                }
                
                archAux.writeObject(inst);
            }

            
            
            
        } catch (Exception e) {
        }finally {
            arch.close();
            archAux.close();
            
            
            
            if(flag != true)
                JOptionPane.showMessageDialog(null, "NO ENCONTRADO");
            else{
                JOptionPane.showMessageDialog(null, "EMPLEADO ADICIONADO");

            }
            
            File F1 = new File(nomArch); // empleadito.dat
            File F2 = new File("copiaInstitucion.dat"); // auxiliar
            F1.delete();
            F2.renameTo(F1);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfazEmpleado().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(InterfazEmpleado.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ButtonGrupoSexo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAdicionar1;
    private javax.swing.JButton jButtonAdicionarAmbiente;
    private javax.swing.JButton jButtonAdicionarAmbiente1;
    private javax.swing.JButton jButtonEmpleadoJoven;
    private javax.swing.JButton jButtonGuardarPila;
    private javax.swing.JButton jButtonVolverInicio;
    private javax.swing.JComboBox<String> jComboBoxInstituciones;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelAmbientes;
    private javax.swing.JPanel jPanelInstitucion;
    private javax.swing.JProgressBar jProgressBarPila;
    private javax.swing.JRadioButton jRadioButtonFemenino;
    private javax.swing.JRadioButton jRadioButtonMasculino;
    private javax.swing.JRadioButton jRadioButtonOtros;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEmpleado;
    private javax.swing.JTextField jTextFieldAmbieneCantidad;
    private javax.swing.JTextField jTextFieldAmbienteNombrer;
    private javax.swing.JTextField jTextFieldAmbienteUbi;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldEdad;
    private javax.swing.JTextField jTextFieldInstitucionUbicacion;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldNombreInst;
    private javax.swing.JTextField jTextFieldSueldo;
    // End of variables declaration//GEN-END:variables
}
