
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class InterfazConsultas extends javax.swing.JFrame {

    /**
     * Creates new form InterfazConsultas
     */
    public InterfazConsultas() {
        initComponents();
        
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonEliminarX = new javax.swing.JButton();
        jLabelTexto = new javax.swing.JLabel();
        jTextFieldEliminarEdadX = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButtonVolver = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonEliminarX.setText("Eliminar");
        jButtonEliminarX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarXActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminarX, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 80, 30));

        jLabelTexto.setFont(new java.awt.Font("Comic Sans MS", 2, 24)); // NOI18N
        jLabelTexto.setForeground(new java.awt.Color(204, 0, 0));
        jLabelTexto.setText("Consultas del Programa");
        jPanel1.add(jLabelTexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 270, 40));

        jTextFieldEliminarEdadX.setText("0.0");
        jPanel1.add(jTextFieldEliminarEdadX, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 170, 30));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Eliminar edad X");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 110, 30));

        jButtonVolver.setText("Volver");
        jButtonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonVolverMouseClicked(evt);
            }
        });
        jButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVolverActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/paisaje.jpg"))); // NOI18N
        jLabelFondo.setText("jLabel1");
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 370));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonVolverMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonVolverMouseClicked

    private void jButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVolverActionPerformed
        // TODO add your handling code here:
        
        InterfazMenu menu = new InterfazMenu();
        menu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonVolverActionPerformed

    private void jButtonEliminarXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarXActionPerformed
        String nomArch = "Empleadito.dat";
        boolean flag = false;
        ObjectInputStream arch = null; // input (lectura)
        ObjectOutputStream archAux = null; // output (escritura)

        int edad = -1;
        try {
            edad = Integer.parseInt(jTextFieldEliminarEdadX.getText());
        } catch (Exception e) {
            edad = -1;
            JOptionPane.showMessageDialog(null, "La edad debe ser un número entero");
        }
        
        try {
            arch = new ObjectInputStream(new FileInputStream(nomArch));
            archAux = new ObjectOutputStream(new FileOutputStream("copia.dat", true));
            
            while(true){
                Empleado emp = (Empleado)arch.readObject();



                if( !(emp.getEdad() == edad) ){
                    // tengo que guardarlo
                    // se puede modfiicar el objecto
                    archAux.writeObject(emp);
                }else{
                    // lo que voy a eliminar
                    flag = true;
                }

            }

            
            
            
        } catch (Exception e) {
        }finally {
            try {
                arch.close();
            } catch (IOException ex) {
                Logger.getLogger(InterfazConsultas.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            try {
                archAux.close();
            } catch (IOException ex) {
                Logger.getLogger(InterfazConsultas.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            if(flag != true)
                JOptionPane.showMessageDialog(null, "NO ENCONTRADO");
            else{
                JOptionPane.showMessageDialog(null, "ELIMINADO");

            }
            
            File F1 = new File(nomArch); // empleadito.dat
            File F2 = new File("copia.dat"); // auxiliar
            F1.delete();
            F2.renameTo(F1);
        }
    }//GEN-LAST:event_jButtonEliminarXActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazConsultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazConsultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEliminarX;
    private javax.swing.JButton jButtonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTexto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldEliminarEdadX;
    // End of variables declaration//GEN-END:variables
}
