/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empleado;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class InterfazEliminar extends javax.swing.JFrame {

    /**
     * Creates new form InterfazEliminar
     */
    public InterfazEliminar() {
        initComponents();
        setLocationRelativeTo(null);
        jLabel1.setOpaque(true);
        jLabel1.setBackground(Color.BLACK);
        jLabel1.setForeground(Color.WHITE);
        jLabel3.setOpaque(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTCodigo = new javax.swing.JTextField();
        jBSalarioModificar6 = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBListar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText(" Eliminar Empleado ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Codigo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jTCodigo.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTCodigo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel1.add(jTCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 170, -1));

        jBSalarioModificar6.setBackground(new java.awt.Color(0, 0, 0));
        jBSalarioModificar6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jBSalarioModificar6.setForeground(new java.awt.Color(255, 255, 255));
        jBSalarioModificar6.setText("Volver");
        jBSalarioModificar6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jBSalarioModificar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalarioModificar6ActionPerformed(evt);
            }
        });
        jPanel1.add(jBSalarioModificar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 90, 40));

        jBEliminar.setBackground(new java.awt.Color(0, 0, 0));
        jBEliminar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jBEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jBEliminar.setText("Eliminar");
        jBEliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 90, 40));

        jBListar.setBackground(new java.awt.Color(0, 0, 0));
        jBListar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jBListar.setForeground(new java.awt.Color(255, 255, 255));
        jBListar.setText("Listar");
        jBListar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jBListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListarActionPerformed(evt);
            }
        });
        jPanel1.add(jBListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 80, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 270));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBSalarioModificar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalarioModificar6ActionPerformed
        // TODO add your handling code here:
        InterfazArchivo cur = new InterfazArchivo();
        cur.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBSalarioModificar6ActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        // TODO add your handling code here:
              //        }
        String nomArch = "Empleado.dat";
        boolean flag = false;
        ObjectInputStream arch = null;
        ObjectOutputStream archAux = null;

        String codigo = jTCodigo.getText();
        try {
                arch = new ObjectInputStream(new FileInputStream(nomArch));
                archAux = new ObjectOutputStream(new FileOutputStream("copia.dat", true));
                while(true) {
                        Empleado em = new Empleado();
                        em = (Empleado)arch.readObject();
                        if(em.getCodigo().equals(codigo))
                            flag = true;
                        else
                            archAux.writeObject(em);

                }
        } catch (Exception e) {
        }finally {
            try {
                arch.close();
            } catch (IOException ex) {
                Logger.getLogger(InterfazEliminar.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                archAux.close();
            } catch (IOException ex) {
                Logger.getLogger(InterfazEliminar.class.getName()).log(Level.SEVERE, null, ex);
            }
            
                if(flag != true)
                    JOptionPane.showMessageDialog(null, "NO ENCONTRADO");
                else{
                    JOptionPane.showMessageDialog(null, "ELIMINADO");
                    
                }
                File F1 = new File(nomArch);
                File F2 = new File("copia.dat");
                F1.delete();
                F2.renameTo(F1);
        }
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListarActionPerformed
        InterfazListar cur = new InterfazListar();
        cur.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazEliminar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazEliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBListar;
    private javax.swing.JButton jBSalarioModificar6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTCodigo;
    // End of variables declaration//GEN-END:variables
}
