/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empleado;

import java.awt.Color;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class InterfazArchivo extends javax.swing.JFrame implements java.io.Serializable{

    /**
     * Creates new form InterfazArchivo
     */
    public InterfazArchivo() {
        initComponents();
        setLocationRelativeTo(null);
        jLabel1.setOpaque(true);
        jLabel1.setBackground(Color.BLACK);
        jLabel1.setForeground(Color.WHITE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jBCrear = new javax.swing.JButton();
        jBAdicionar = new javax.swing.JButton();
        jBListar = new javax.swing.JButton();
        jBEliminar = new javax.swing.JButton();
        jBConsultas = new javax.swing.JButton();
        jBConsultas1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText(" Empleado ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        jBCrear.setBackground(new java.awt.Color(0, 0, 0));
        jBCrear.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jBCrear.setForeground(new java.awt.Color(255, 255, 255));
        jBCrear.setText("Crear");
        jBCrear.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jBCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCrearActionPerformed(evt);
            }
        });
        jPanel1.add(jBCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 115, -1));

        jBAdicionar.setBackground(new java.awt.Color(0, 0, 0));
        jBAdicionar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jBAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        jBAdicionar.setText("Adicionar");
        jBAdicionar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jBAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAdicionarActionPerformed(evt);
            }
        });
        jPanel1.add(jBAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 115, -1));

        jBListar.setBackground(new java.awt.Color(0, 0, 0));
        jBListar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jBListar.setForeground(new java.awt.Color(255, 255, 255));
        jBListar.setText("Listar");
        jBListar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jBListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBListarActionPerformed(evt);
            }
        });
        jPanel1.add(jBListar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 115, -1));

        jBEliminar.setBackground(new java.awt.Color(0, 0, 0));
        jBEliminar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jBEliminar.setForeground(new java.awt.Color(255, 255, 255));
        jBEliminar.setText("Eliminar");
        jBEliminar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jBEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jBEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 115, -1));

        jBConsultas.setBackground(new java.awt.Color(0, 0, 0));
        jBConsultas.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jBConsultas.setForeground(new java.awt.Color(255, 255, 255));
        jBConsultas.setText("Consultas");
        jBConsultas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jBConsultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultasActionPerformed(evt);
            }
        });
        jPanel1.add(jBConsultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 115, -1));

        jBConsultas1.setBackground(new java.awt.Color(255, 0, 0));
        jBConsultas1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jBConsultas1.setForeground(new java.awt.Color(255, 255, 255));
        jBConsultas1.setText("Salir");
        jBConsultas1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jBConsultas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBConsultas1ActionPerformed(evt);
            }
        });
        jPanel1.add(jBConsultas1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 115, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Salir.png"))); // NOI18N
        jLabel3.setText("jLabel2");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 100, 100));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Crear.png"))); // NOI18N
        jLabel4.setText("jLabel2");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 100, 100));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Adicionar.png"))); // NOI18N
        jLabel5.setText("jLabel2");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 80, 100, 100));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mostrar.png"))); // NOI18N
        jLabel6.setText("jLabel2");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 100, 100));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Eliminar.png"))); // NOI18N
        jLabel7.setText("jLabel2");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 100, 100));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Buscar.png"))); // NOI18N
        jLabel8.setText("jLabel2");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 100, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 440));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCrearActionPerformed
        String nomArch = "Empleado.dat";
        ObjectOutputStream arch = null;
        try{
            arch = new ObjectOutputStream(new FileOutputStream(nomArch));
            arch.close();
            JOptionPane.showMessageDialog(null, "ARCHIVO CREADO");
        }catch(Exception e){
            
        }finally{
        }
    }//GEN-LAST:event_jBCrearActionPerformed

    private void jBAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAdicionarActionPerformed
        InterfazEmpleado cur;
        try {
            cur = new InterfazEmpleado();
            cur.setVisible(true);
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(InterfazArchivo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBAdicionarActionPerformed

    private void jBListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBListarActionPerformed
        InterfazListar cur = new InterfazListar();
        cur.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBListarActionPerformed

    private void jBEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarActionPerformed
        InterfazEliminar aux = new InterfazEliminar();
        aux.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBEliminarActionPerformed

    private void jBConsultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultasActionPerformed
        // TODO add your handling code here:
        InterfazConsultas axu = new InterfazConsultas();
        axu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBConsultasActionPerformed

    private void jBConsultas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBConsultas1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jBConsultas1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazArchivo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazArchivo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAdicionar;
    private javax.swing.JButton jBConsultas;
    private javax.swing.JButton jBConsultas1;
    private javax.swing.JButton jBCrear;
    private javax.swing.JButton jBEliminar;
    private javax.swing.JButton jBListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
