/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empleado;

import java.awt.Color;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class InterfazEmpleado extends javax.swing.JFrame implements java.io.Serializable{

    /**
     * Creates new form InterfazEmpleado
     */
    
//    Empleado E1 = new Empleado();
//    int limite = 5;
    private int codigo;
    private Empleado empleado = new Empleado();
    private int nroEmpleados;
//    private Avioni avion = new Avioni();
    public InterfazEmpleado() throws IOException {
        codigo = 1;
        initComponents();
        setLocationRelativeTo(null);
        int cnt = 0;
        ObjectInputStream arch = null;
        String nomArch = "Empleado.dat";
        try {
            arch = new ObjectInputStream(new FileInputStream(nomArch));
            while(true){
                Empleado E1 = new Empleado();
                E1 = (Empleado)arch.readObject();
                cnt = Integer.parseInt(E1.getCodigo().substring(1));
            }
        } catch (Exception e) {
        }finally{
            arch.close();
        }
        jPEmpleado.setValue(cnt);
        codigo = cnt + 1;
        jLabel3.setOpaque(true);
        jLabel3.setBackground(Color.BLACK);
        
        
        jLabel2.setOpaque(true);
        jLabel2.setBackground(Color.BLACK);
        
        
        jLabel4.setOpaque(true);
        jLabel4.setBackground(Color.BLACK);
        
        
        jLabel5.setOpaque(true);
        jLabel5.setBackground(Color.BLACK);
        
        
        jLabel6.setOpaque(true);
        jLabel6.setBackground(Color.BLACK);
        
        
        jLabel7.setOpaque(true);
        jLabel7.setBackground(Color.BLACK);
        
        
        jLabel3.setOpaque(true);
        jLabel3.setBackground(Color.BLACK);
        
        jCFemenino.setOpaque(true);
        jCMasculino.setOpaque(true);
        jCNoDefinido.setOpaque(true);
    }

    public JProgressBar getjPEmpleado() {
        return jPEmpleado;
    }

    public void setjPEmpleado(JProgressBar jPEmpleado) {
        this.jPEmpleado = jPEmpleado;
    }
    
//    public void addEmpleado(Empleado e){
//        if(nroEmpleados < limite){
//            empleado = e;
//            nroEmpleados++;
//        }else
//            JOptionPane.showMessageDialog(null, "El vector esta lleno");
//            
//        
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTNombre = new javax.swing.JTextField();
        jTApellido = new javax.swing.JTextField();
        jTFechaNac = new javax.swing.JTextField();
        jTFechaIngreso = new javax.swing.JTextField();
        jTSalario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jCMasculino = new javax.swing.JCheckBox();
        jCFemenino = new javax.swing.JCheckBox();
        jCNoDefinido = new javax.swing.JCheckBox();
        jPEmpleado = new javax.swing.JProgressBar();
        jBAgregar = new javax.swing.JButton();
        jBActualizar = new javax.swing.JButton();
        jBSalarioModificar6 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 190));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Salario:");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Apellido:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Genero:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fecha Nac:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jLabel7.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Fecha Ingreso:");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jTNombre.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jTNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 170, -1));

        jTApellido.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jTApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 170, -1));

        jTFechaNac.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTFechaNac.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jTFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, 170, -1));

        jTFechaIngreso.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTFechaIngreso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jTFechaIngreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 170, -1));

        jTSalario.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jTSalario.setText("0.0");
        jTSalario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jPanel3.add(jTSalario, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 170, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo 2.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 260, 290));

        jCMasculino.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jCMasculino);
        jCMasculino.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jCMasculino.setForeground(new java.awt.Color(255, 255, 255));
        jCMasculino.setText("Masculino");
        jPanel3.add(jCMasculino, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jCFemenino.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jCFemenino);
        jCFemenino.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jCFemenino.setForeground(new java.awt.Color(255, 255, 255));
        jCFemenino.setText("Femenino");
        jPanel3.add(jCFemenino, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        jCNoDefinido.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(jCNoDefinido);
        jCNoDefinido.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jCNoDefinido.setForeground(new java.awt.Color(255, 255, 255));
        jCNoDefinido.setText("No Definido");
        jPanel3.add(jCNoDefinido, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jPEmpleado.setMaximum(50);
        jPanel3.add(jPEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 260, 40));

        jBAgregar.setBackground(new java.awt.Color(0, 0, 0));
        jBAgregar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jBAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jBAgregar.setText("Agregar");
        jBAgregar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jBAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(jBAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 100, 40));

        jBActualizar.setBackground(new java.awt.Color(0, 0, 0));
        jBActualizar.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jBActualizar.setForeground(new java.awt.Color(255, 255, 255));
        jBActualizar.setText("Actualizar");
        jBActualizar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });
        jPanel3.add(jBActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 140, 30));

        jBSalarioModificar6.setBackground(new java.awt.Color(0, 0, 0));
        jBSalarioModificar6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jBSalarioModificar6.setForeground(new java.awt.Color(255, 255, 255));
        jBSalarioModificar6.setText("Volver");
        jBSalarioModificar6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        jBSalarioModificar6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalarioModificar6ActionPerformed(evt);
            }
        });
        jPanel3.add(jBSalarioModificar6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 90, 40));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 420));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 600, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarActionPerformed
        String nomArch = "Empleado.dat";
        try{
            ObjectOutputStream arch = null;
            if(new File(nomArch).exists())
                arch = new AddObjectOutputStream(new FileOutputStream(nomArch, true));
            else
                arch = new ObjectOutputStream(new FileOutputStream(nomArch, true));
            
            Empleado E1 = new Empleado();
            E1.setCodigo("E" + codigo);
            codigo++;
            E1.setNombre(jTNombre.getText());
            E1.setApellido(jTApellido.getText());
    //        E1.setGenero(jTGenero.getText());
            E1.setFechaNac(jTFechaNac.getText());
            E1.setFechaIngresoEmpresa(jTFechaIngreso.getText());
            E1.setSalario(Double.parseDouble(jTSalario.getText()));
            
            if(jCFemenino.isSelected()){ // si esque se ha seleccionado la opcion
                E1.setGenero(jCFemenino.getText()); // obtener el text
            }
        
            if(jCMasculino.isSelected()){
                E1.setGenero(jCMasculino.getText());
            }
            if(jCNoDefinido.isSelected())
                E1.setGenero(jCNoDefinido.getText());

            // RADIO BUTTON

//            if(jRFemenino.isSelected())
//                E1.setGenero(jRFemenino.getText());
//
//
//            if(jRMasculino.isSelected())
//                E1.setGenero(jRMasculino.getText());
//
//
//            if(jRNoDefinido.isSelected())
//                E1.setGenero(jRNoDefinido.getText());
            
        
        // Progress Bar
            jPEmpleado.getValue(); // obtiene el valor de la barra de progreso
            jPEmpleado.setValue(jPEmpleado.getValue() + 1);

            jTNombre.setText("");
            jTApellido.setText("");
    //        jTGenero.setText("");
            jTFechaNac.setText("");
            jTFechaIngreso.setText("");
            jTSalario.setText("0.0");

            arch.writeObject(E1);
            arch.close();
        } catch (Exception e) {
                
                
        }
        
        
        
        // CHECK BOX
        
        // limpia pantalla
        
//        addEmpleado(E1);
       
//        if(nroEmpleados < limite)
//            JOptionPane.showMessageDialog(null, "Agregado correctamente");
        
    }//GEN-LAST:event_jBAgregarActionPerformed

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
        // TODO add your handling code here:
        ObjectInputStream arch = null;
        String nomArch = "Empleado.dat";
        int cur = 0;
        try {
            arch = new ObjectInputStream(new FileInputStream(nomArch));
            while(true){
                Empleado E1 = new Empleado();
                E1 = (Empleado)arch.readObject();
                cur++;
            }
        } catch (Exception e) {
        }finally{
            try {
                arch.close();
            } catch (IOException ex) {
                Logger.getLogger(InterfazEmpleado.class.getName()).log(Level.SEVERE, null, ex);
            }
            jPEmpleado.setValue(cur);
        }
        
    }//GEN-LAST:event_jBActualizarActionPerformed

    private void jBSalarioModificar6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalarioModificar6ActionPerformed
        // TODO add your handling code here:
        InterfazArchivo cur = new InterfazArchivo();
        cur.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBSalarioModificar6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfazEmpleado().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(InterfazEmpleado.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBAgregar;
    private javax.swing.JButton jBSalarioModificar6;
    private javax.swing.JCheckBox jCFemenino;
    private javax.swing.JCheckBox jCMasculino;
    private javax.swing.JCheckBox jCNoDefinido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JProgressBar jPEmpleado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTApellido;
    private javax.swing.JTextField jTFechaIngreso;
    private javax.swing.JTextField jTFechaNac;
    private javax.swing.JTextField jTNombre;
    private javax.swing.JTextField jTSalario;
    // End of variables declaration//GEN-END:variables
}
